[project]
name = "gisorders"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.17.2",
    "asyncpg==0.30.0",
    "bcrypt==4.2.0",
    "dotenv==0.9.9",
    "fastapi==0.117.0",
    "geoalchemy2>=0.18.1",
    "greenlet>=3.2.4",
    "passlib==1.7.4",
    "pydantic-settings>=2.14.2",
    "pydantic[email]==2.12.0a1",
    "python-jose==3.5.0",
    "python-multipart==0.0.20",
    "shapely>=2.1.2",
    "sqlalchemy==2.0.43",
    "uvicorn==0.37.0",
]

[tool.uv.workspace]
members = [
    "gisorders",
]

[dependency-groups]
dev = [
    "factory-boy>=3.3.3",
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
]
[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = ["."]
testpaths = ["tests"]
