"""add order tables

Revision ID: ae5557f98182
Revises: 59e744c05168
Create Date: 2026-03-01 23:05:25.227720

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae5557f98182'
down_revision: Union[str, Sequence[str], None] = '59e744c05168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('order',
	                sa.Column('id', sa.Integer(), nullable=False),
	                sa.Column('title', sa.String(length=200), nullable=False),
	                sa.Column('description', sa.Text(), nullable=False),
	                sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='order_status'),
	                          nullable=False),
	                sa.Column('min_price', sa.Float(), nullable=True),
	                sa.Column('max_price', sa.Float(), nullable=True),
	                sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
	                sa.Column('deadline', sa.DateTime(), nullable=False),
	                sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2,
	                                                                 from_text='ST_GeomFromEWKT', name='geometry'),
	                          nullable=True),
	                sa.Column('address', sa.String(length=500), nullable=False),
	                sa.Column('tree_type', sa.String(length=50), nullable=False),
	                sa.Column('tree_height', sa.Float(), nullable=False),
	                sa.Column('tree_diameter', sa.Float(), nullable=False),
	                sa.Column('photos', postgresql.ARRAY(sa.String()), nullable=True),
	                sa.Column('customer_id', sa.Integer(), nullable=False),
	                sa.ForeignKeyConstraint(['customer_id'], ['user.id'], name=op.f('fk_order_customer_id_user')),
	                sa.PrimaryKeyConstraint('id', name=op.f('pk_order'))
	                )
	op.create_index('idx_order_location', 'order', ['location'], unique=False, postgresql_using='gist',
	                if_not_exists=True)
	op.create_table('order_proposal',
	                sa.Column('id', sa.Integer(), nullable=False),
	                sa.Column('proposed_price', sa.Float(), nullable=False),
	                sa.Column('message', sa.Text(), nullable=True),
	                sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
	                sa.Column('order_id', sa.Integer(), nullable=False),
	                sa.Column('executor_id', sa.Integer(), nullable=False),
	                sa.ForeignKeyConstraint(['executor_id'], ['user.id'],
	                                        name=op.f('fk_order_proposal_executor_id_user')),
	                sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_order_proposal_order_id_order')),
	                sa.PrimaryKeyConstraint('id', name=op.f('pk_order_proposal'))
	                )
	# op.drop_table('spatial_ref_sys')


# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	# op.create_table('spatial_ref_sys',
	#                 sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
	#                 sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
	#                 sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
	#                 sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
	#                 sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
	#                 sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
	#                 sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
	#                 )
	op.drop_table('order_proposal')
	op.drop_index('idx_order_location', table_name='order', postgresql_using='gist')
	op.drop_table('order')
	sa.Enum(name='order_status').drop(op.get_bind())

# ### end Alembic commands ###
